INSERT INTO aud."LogLevel"
	("IdLogLevel", "LogLevel")
values
	(0, 'Trace'),
	(1, 'Debug'),
	(2, 'Information'),
	(3, 'Warning'),
	(4, 'Error'),
	(5, 'Critical')
; 

INSERT INTO sub."AddressType"
	("IdAddressType", "Value")
VALUES
	(1, 'Permanent residence'),
	(2, 'Correspondence address');




INSERT INTO sub."Country"
	("IdCountry", "Code", "Acronym2", "Acronym3", "NameSKShort", "NameSK", "IsValid", "NameEN", "NameENShort")
Values
(1, '004', 'AF', 'AFG', 'Afganistan', 'Afganská islamská republika', True, 'Islamic Republic of Afghanistan', 'Afghanistan'),
(2, '008', 'AL', 'ALB', 'Albánsko', 'Albánska republika', True, 'Republic of Albania', 'Albania'),
(3, '010', 'AQ', 'ATA', 'Antarktída', 'Antarktída', True, 'Antarctica', 'Antarctica'),
(4, '012', 'DZ', 'DZA', 'Alžírsko', 'Alžírska demokratická ľudová republika', True, 'People`s Democratic Republic of Algeria', 'Algeria'),
(5, '016', 'AS', 'ASM', 'Americká Samoa', 'Teritórium Americkej Samoy', True, 'Territory of American Samoa', 'American Samoa'),
(6, '020', 'AD', 'AND', 'Andorra', 'Andorrské kniežatstvo', True, 'Principality of Andorra', 'Andorra'),
(7, '024', 'AO', 'AGO', 'Angola', 'Angolská republika', True, 'Republic of Angola', 'Angola'),
(8, '028', 'AG', 'ATG', 'Antigua a Barbuda', 'Antigua a Barbuda', True, 'Antigua and Barbuda', 'Antigua and Barbuda'),
(9, '031', 'AZ', 'AZE', 'Azerbajdžan', 'Azerbajdžanská republika', True, 'Republic of Azerbaijan', 'Azerbaijan'),
(10, '032', 'AR', 'ARG', 'Argentína', 'Argentínska republika', True, 'Argentine Republic', 'Argentina'),
(11, '036', 'AU', 'AUS', 'Austrália', 'Austrálsky zväz', True, 'Australia', 'Australia'),
(12, '040', 'AT', 'AUT', 'Rakúsko', 'Rakúska republika', True, 'Republic of Austria', 'Austria'),
(13, '044', 'BS', 'BHS', 'Bahamy', 'Bahamské spoločenstvo', True, 'Commonwealth of The Bahamas', 'Bahamas'),
(14, '048', 'BH', 'BHR', 'Bahrajn', 'Bahrajnské kráľovstvo', True, 'Kingdom of Bahrain', 'Bahrain'),
(15, '050', 'BD', 'BGD', 'Bangladéš', 'Bangladéšska ľudová republika', True, 'People`s Republic of Bangladesh', 'Bangladesh'),
(16, '051', 'AM', 'ARM', 'Arménsko', 'Arménska republika', True, 'Republic of Armenia', 'Armenia'),
(17, '052', 'BB', 'BRB', 'Barbados', 'Barbados', True, 'Barbados', 'Barbados'),
(18, '056', 'BE', 'BEL', 'Belgicko', 'Belgické kráľovstvo', True, 'Kingdom of Belgium', 'Belgium'),
(19, '060', 'BM', 'BMU', 'Bermudy', 'Bermudy', True, 'Bermuda', 'Bermuda'),
(20, '064', 'BT', 'BTN', 'Bhután', 'Bhutánske kráľovstvo', True, 'Kingdom of Bhutan', 'Bhutan'),
(21, '068', 'BO', 'BOL', 'Bolívia', 'Bolívijský mnohonárodný štát', True, 'Plurinational State of Bolivia', 'Bolivia (Plurinat.State)'),
(22, '070', 'BA', 'BIH', 'Bosna a Hercegovina', 'Bosna a Hercegovina', True, 'Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
(23, '072', 'BW', 'BWA', 'Botswana', 'Botswanská republika', True, 'Republic of Botswana', 'Botswana'),
(24, '074', 'BV', 'BVT', 'Bouvetov ostrov', 'Bouvetov ostrov', True, 'Bouvet Island', 'Bouvet Island'),
(25, '076', 'BR', 'BRA', 'Brazília', 'Brazílska federatívna republika', True, 'Federative Republic of Brazil', 'Brazil'),
(26, '084', 'BZ', 'BLZ', 'Belize', 'Belize', True, 'Belize', 'Belize'),
(27, '086', 'IO', 'IOT', 'Brit.indickooceán.územie', 'Britské indickooceánske územie', True, 'British Indian Ocean Territory', 'British Ind.Ocean Terr.'),
(28, '090', 'SB', 'SLB', 'Šalamúnove ostrovy', 'Šalamúnove ostrovy', True, 'Solomon Islands', 'Solomon Islands'),
(29, '092', 'VG', 'VGB', 'Britské Panenské ostr.', 'Britské Panenské ostrovy', True, 'British Virgin Islands', 'Virgin Islands, British'),
(30, '096', 'BN', 'BRN', 'Brunej', 'Brunejsko-darussalamský štát', True, 'Brunei Darussalam', 'Brunei Darussalam'),
(31, '100', 'BG', 'BGR', 'Bulharsko', 'Bulharská republika', True, 'Republic of Bulgaria', 'Bulgaria'),
(32, '104', 'MM', 'MMR', 'Mjanmarsko', 'Mjanmarská zväzová republika', True, 'Republic of the Union of Myanmar', 'Myanmar'),
(33, '108', 'BI', 'BDI', 'Burundi', 'Burundská republika', True, 'Republic of Burundi', 'Burundi'),
(34, '112', 'BY', 'BLR', 'Bielorusko', 'Bieloruská republika', True, 'Republic of Belarus', 'Belarus'),
(35, '116', 'KH', 'KHM', 'Kambodža', 'Kambodžské kráľovstvo', True, 'Kingdom of Cambodia', 'Cambodia'),
(36, '120', 'CM', 'CMR', 'Kamerun', 'Kamerunská republika', True, 'Republic of Cameroon', 'Cameroon'),
(37, '124', 'CA', 'CAN', 'Kanada', 'Kanada', True, 'Canada', 'Canada'),
(38, '132', 'CV', 'CPV', 'Kapverdy', 'Kapverdská republika', True, 'Republic of Cape Verde', 'Cape Verde'),
(39, '136', 'KY', 'CYM', 'Kajmanie ostrovy', 'Kajmanie ostrovy', True, 'Cayman Islands', 'Cayman Islands'),
(40, '140', 'CF', 'CAF', 'Stredoafrická republika', 'Stredoafrická republika', True, 'Central African Republic', 'Central African Rep.'),
(41, '144', 'LK', 'LKA', 'Srí Lanka', 'Srílanská demokratická socialistická republika', True, 'Democratic Socialist Republic of Sri Lanka', 'Sri Lanka'),
(42, '148', 'TD', 'TCD', 'Čad', 'Čadská republika', True, 'Republic of Chad', 'Chad'),
(43, '152', 'CL', 'CHL', 'Čile', 'Čilská republika', True, 'Republic of Chile', 'Chile'),
(44, '156', 'CN', 'CHN', 'Čína', 'Čínska ľudová republika', True, 'Peoples Republic of China', 'China'),
(45, '158', 'TW', 'TWN', 'Taiwan', 'Čínska republika', True, 'Republic of China', 'Taiwan'),
(46, '162', 'CX', 'CXR', 'Vianočný ostrov', 'Teritórium Vianočného ostrova', True, 'Christmas Island Territory', 'Christmas Island'),
(47, '166', 'CC', 'CCK', 'Kokosové ostrovy', 'Teritórium Kokosových ostrovov', True, 'Territory of Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'),
(48, '170', 'CO', 'COL', 'Kolumbia', 'Kolumbijská republika', True, 'Republic of Colombia', 'Colombia'),
(49, '174', 'KM', 'COM', 'Komory', 'Komorský zväz', True, 'Union of the Comoros', 'Comoros'),
(50, '175', 'YT', 'MYT', 'Mayotte', 'Mayotte', True, 'Mayotte', 'Mayotte'),
(51, '178', 'CG', 'COG', 'Kongo', 'Konžská republika', True, 'Republic of the Congo', 'Congo'),
(52, '180', 'CD', 'COD', 'Kongo (býv. Zair)', 'Konžská demokratická republika', True, 'Democratic Republic of the Congo', 'Dem.Rep. of the Congo'),
(53, '184', 'CK', 'COK', 'Cookove ostrovy', 'Cookove ostrovy', True, 'Cook Islands', 'Cook Islands'),
(54, '188', 'CR', 'CRI', 'Kostarika', 'Kostarická republika', True, 'Republic of Costa Rica', 'Costa Rica'),
(55, '191', 'HR', 'HRV', 'Chorvátsko', 'Chorvátska republika', True, 'Republic of Croatia', 'Croatia'),
(56, '192', 'CU', 'CUB', 'Kuba', 'Kubánska republika', True, 'Republic of Cuba', 'Cuba'),
(57, '196', 'CY', 'CYP', 'Cyprus', 'Cyperská republika', True, 'Republic of Cyprus', 'Cyprus'),
(58, '200', 'CS', 'N/A', 'Československo', 'Česká a Slovenská Federatívna republika', False, 'Czech and Slovak Federal Republic', 'Czechoslovakia'),
(59, '203', 'CZ', 'CZE', 'Česko', 'Česká republika', True, 'Czech Republic', 'Czech Republic'),
(60, '204', 'BJ', 'BEN', 'Benin', 'Beninská republika', True, 'Republic of Benin', 'Benin'),
(61, '208', 'DK', 'DNK', 'Dánsko', 'Dánske kráľovstvo', True, 'Kingdom of Denmark', 'Denmark'),
(62, '212', 'DM', 'DMA', 'Dominika', 'Dominické spoločenstvo', True, 'Commonwealth of Dominica', 'Dominica'),
(63, '214', 'DO', 'DOM', 'Dominikánska republika', 'Dominikánska republika', True, 'Dominican Republic', 'Dominican republic'),
(64, '218', 'EC', 'ECU', 'Ekvádor', 'Ekvádorská republika', True, 'Republic of Ecuador', 'Ecuador'),
(65, '222', 'SV', 'SLV', 'Salvádor', 'Salvádorská republika', True, 'Republic of El Salvador', 'El Salvador'),
(66, '226', 'GQ', 'GNQ', 'Rovníková Guinea', 'Republika Rovníkovej Guiney', True, 'Republic of Equatorial Guinea', 'Equatorial Guinea'),
(67, '230', 'ET', 'N/A', 'Etiópia', 'Etiópia', False, 'Ethiopia', 'Ethiopia'),
(68, '231', 'ET', 'ETH', 'Etiópia', 'Etiópska federatívna demokratická republika', True, 'Federal Democratic Republic of Ethiopia', 'Ethiopia'),
(69, '232', 'ER', 'ERI', 'Eritrea', 'Eritrejský štát', True, 'Eritrea', 'The State of Eritrea'),
(70, '233', 'EE', 'EST', 'Estónsko', 'Estónska republika', True, 'Republic of Estonia', 'Estonia'),
(71, '234', 'FO', 'FRO', 'Faerské ostrovy', 'Faerské ostrovy', True, 'Faroe Islands', 'Faroe Islands'),
(72, '238', 'FK', 'FLK', 'Falklandy', 'Falklandské ostrovy', True, 'Falkland Islands (Malvinas)', 'Falkland Isl. (Malvinas)'),
(73, '239', 'GS', 'SGS', 'Juž. Georgia a J.S.o.', 'Južná Georgia a Južné Sandwichove ostrovy', True, 'South Georgia and the South Sandwich Islands', 'S.Georgia, s.Sand. Isl.'),
(74, '242', 'FJ', 'FJI', 'Fidži', 'Fidžijská republika', True, 'Republic of Fiji', 'Fiji'),
(75, '246', 'FI', 'FIN', 'Fínsko', 'Fínska republika', True, 'Republic of Finland', 'Finland'),
(76, '248', 'AX', 'ALA', 'Alandy', 'Alandy', True, 'Aland Islands', 'Aland Islands'),
(77, '249', 'FX', 'N/A', 'Metropolitné Francúzsko', 'Metropolitné Francúzsko', False, 'France, Metropolitan', 'France, Metropolitan'),
(78, '250', 'FR', 'FRA', 'Francúzsko', 'Francúzska republika', True, 'French Republic', 'France'),
(79, '254', 'GF', 'GUF', 'Francúzska Guyana', 'Francúzska Guyana', True, 'French Guiana', 'French Guiana'),
(80, '258', 'PF', 'PYF', 'Francúzska Polynézia', 'Francúzska Polynézia', True, 'French Polynesia', 'French Polynesia'),
(81, '260', 'TF', 'ATF', 'Francúzske južné územia', 'Francúzske južné a antarktické územia', True, 'French Southern Territories', 'French Southern Territ.'),
(82, '262', 'DJ', 'DJI', 'Džibutsko', 'Džibutská republika', True, 'Republic of Djibouti', 'Djibouti'),
(83, '266', 'GA', 'GAB', 'Gabon', 'Gabonská republika', True, 'Gabonese Republic', 'Gabon'),
(84, '268', 'GE', 'GEO', 'Gruzínsko', 'Gruzínsko', True, 'Georgia', 'Georgia'),
(85, '270', 'GM', 'GMB', 'Gambia', 'Gambijská republika', True, 'Republic of the Gambia', 'Gambia'),
(86, '275', 'PS', 'PSE', 'Palestína', 'Palestínsky štát', True, 'The State of Palestine', 'Palestine, State of'),
(87, '276', 'DE', 'DEU', 'Nemecko', 'Nemecká spolková republika', True, 'Federal Republic of Germany', 'Germany'),
(88, '288', 'GH', 'GHA', 'Ghana', 'Ghanská republika', True, 'Republic of Ghana', 'Ghana'),
(89, '292', 'GI', 'GIB', 'Gibraltár', 'Gibraltár', True, 'Gibraltar', 'Gibraltar'),
(90, '296', 'KI', 'KIR', 'Kiribati', 'Kiribatská republika', True, 'Republic of Kiribati', 'Kiribati'),
(91, '300', 'GR', 'GRC', 'Grécko', 'Grécka republika', True, 'Hellenic Republic', 'Greece'),
(92, '304', 'GL', 'GRL', 'Grónsko', 'Grónsko', True, 'Greenland', 'Greenland'),
(93, '308', 'GD', 'GRD', 'Grenada', 'Grenada', True, 'Grenada', 'Grenada'),
(94, '312', 'GP', 'GLP', 'Guadeloupe', 'Guadeloup', True, 'Guadeloupe', 'Guadeloupe'),
(95, '316', 'GU', 'GUM', 'Guam', 'Guamské teritórium', True, 'Territory of Guam', 'Guam'),
(96, '320', 'GT', 'GTM', 'Guatemala', 'Guatemalská republika', True, 'Republic of Guatemala', 'Guatemala'),
(97, '324', 'GN', 'GIN', 'Guinea', 'Guinejská republika', True, 'Republic of Guinea', 'Guinea'),
(98, '328', 'GY', 'GUY', 'Guyana', 'Guyanská kooperatívna republika', True, 'Republic of Guyana', 'Guyana'),
(99, '332', 'HT', 'HTI', 'Haiti', 'Haitská republika', True, 'Republic of Haiti', 'Haiti'),
(100, '334', 'HM', 'HMD', 'Heard.ostr.a Macd.ostr.', 'Teritórium Heardovho ostrova a Macdonaldových ostrovov', True, 'Territory of Heard and McDonald Islands', 'Heard Isl.and McDon.Isl.'),
(101, '336', 'VA', 'VAT', 'Vatikán', 'Svätá Stolica (Vatikánsky mestský štát)', True, 'Holy See', 'Holy See'),
(102, '340', 'HN', 'HND', 'Honduras', 'Honduraská republika', True, 'Republic of Honduras', 'Honduras'),
(103, '344', 'HK', 'HKG', 'Hongkong', 'Hongkong', True, 'Hong Kong Special Administrative Region of China', 'Hong Kong'),
(104, '348', 'HU', 'HUN', 'Maďarsko', 'Maďarsko', True, 'Hungary', 'Hungary'),
(105, '352', 'IS', 'ISL', 'Island', 'Islandská republika', True, 'Republic of Iceland', 'Iceland'),
(106, '356', 'IN', 'IND', 'India', 'Indická republika', True, 'Republic of India', 'India'),
(107, '360', 'ID', 'IDN', 'Indonézia', 'Indonézska republika', True, 'Republic of Indonesia', 'Indonesia'),
(108, '364', 'IR', 'IRN', 'Irán', 'Iránska islamská republika', True, 'Islamic Republic of Iran', 'Iran,Islamic Republic of'),
(109, '368', 'IQ', 'IRQ', 'Irak', 'Iracká republika', True, 'Republic of Iraq', 'Iraq'),
(110, '372', 'IE', 'IRL', 'Írsko', 'Írsko', True, 'Ireland', 'Ireland'),
(111, '376', 'IL', 'ISR', 'Izrael', 'Izraelský štát', True, 'State of Israel', 'Israel'),
(112, '380', 'IT', 'ITA', 'Taliansko', 'Talianska republika', True, 'Republic of Italy', 'Italy'),
(113, '384', 'CI', 'CIV', 'Pobrežie slonoviny', 'Republika Pobrežia slonoviny', True, 'Republic of Côte d Ivoire', 'Côte d Ivoire'),
(114, '388', 'JM', 'JAM', 'Jamajka', 'Jamajka', True, 'Jamaica', 'Jamaica'),
(115, '392', 'JP', 'JPN', 'Japonsko', 'Japonsko', True, 'Japan', 'Japan'),
(116, '398', 'KZ', 'KAZ', 'Kazachstan', 'Kazašská republika', True, 'Republic of Kazakhstan', 'Kazakhstan'),
(117, '400', 'JO', 'JOR', 'Jordánsko', 'Jordánske hášimovské kráľovstvo', True, 'Hashemite Kingdom of Jordan', 'Jordan'),
(118, '404', 'KE', 'KEN', 'Keňa', 'Kenská republika', True, 'Republic of Kenya', 'Kenya'),
(119, '408', 'KP', 'PRK', 'Kórej.ľudovodem.rep.', 'Kórejská ľudovodemokratická republika', True, 'Democratic Peoples Republic of Korea', 'Dem.Peopl.Rep. of Korea'),
(120, '410', 'KR', 'KOR', 'Kórejská republika', 'Kórejská republika', True, 'Republic of Korea', 'Korea, Republic of'),
(121, '414', 'KW', 'KWT', 'Kuvajt', 'Kuvajtský štát', True, 'State of Kuwait', 'Kuwait'),
(122, '417', 'KG', 'KGZ', 'Kirgizsko', 'Kirgizská republika', True, 'Kyrgyz Republic', 'Kyrgyzstan'),
(123, '418', 'LA', 'LAO', 'Laos', 'Laoská ľudovodemokratická republika', True, 'Lao Peoples Democratic Republic', 'Lao Peoples Dem. Rep.'),
(124, '422', 'LB', 'LBN', 'Libanon', 'Libanonská republika', True, 'Lebanese Republic', 'Lebanon'),
(125, '426', 'LS', 'LSO', 'Lesotho', 'Lesothské kráľovstvo', True, 'Kingdom of Lesotho', 'Lesotho'),
(126, '428', 'LV', 'LVA', 'Lotyšsko', 'Lotyšská republika', True, 'Republic of Latvia', 'Latvia'),
(127, '430', 'LR', 'LBR', 'Libéria', 'Libérijská republika', True, 'Republic of Liberia', 'Liberia'),
(128, '434', 'LY', 'LBY', 'Líbya', 'Líbya', True, 'Libya', 'Libya'),
(129, '438', 'LI', 'LIE', 'Lichtenštajnsko', 'Lichtenštajnské kniežatstvo', True, 'Principality of Liechtenstein', 'Liechtenstein'),
(130, '440', 'LT', 'LTU', 'Litva', 'Litovská republika', True, 'Republic of Lithuania', 'Lithuania'),
(131, '442', 'LU', 'LUX', 'Luxembursko', 'Luxemburské veľkovojvodstvo', True, 'Grand Duchy of Luxembourg', 'Luxembourg'),
(132, '446', 'MO', 'MAC', 'Macao', 'Macao', True, 'Macao Special Administrative Region of China', 'Macao'),
(133, '450', 'MG', 'MDG', 'Madagaskar', 'Madagaskarská republika', True, 'Republic of Madagascar', 'Madagascar'),
(134, '454', 'MW', 'MWI', 'Malawi', 'Malawijská republika', True, 'Republic of Malawi', 'Malawi'),
(135, '458', 'MY', 'MYS', 'Malajzia', 'Malajzia', True, 'Malaysia', 'Malaysia'),
(136, '462', 'MV', 'MDV', 'Maldivy', 'Maldivská republika', True, 'Republic of Maldives', 'Maldives'),
(137, '466', 'ML', 'MLI', 'Mali', 'Malijská republika', True, 'Republic of Mali', 'Mali'),
(138, '470', 'MT', 'MLT', 'Malta', 'Maltská republika', True, 'Republic of Malta', 'Malta'),
(139, '474', 'MQ', 'MTQ', 'Martinik', 'Martinik', True, 'Martinique', 'Martinique'),
(140, '478', 'MR', 'MRT', 'Mauritánia', 'Mauritánska islamská republika', True, 'Islamic Republic of Mauritania', 'Mauritania'),
(141, '480', 'MU', 'MUS', 'Maurícius', 'Maurícijská republika', True, 'Republic of Mauritius', 'Mauritius'),
(142, '484', 'MX', 'MEX', 'Mexiko', 'Spojené štáty mexické', True, 'United Mexican States', 'Mexico'),
(143, '492', 'MC', 'MCO', 'Monako', 'Monacké kniežatstvo', True, 'Principality of Monaco', 'Monaco'),
(144, '496', 'MN', 'MNG', 'Mongolsko', 'Mongolsko', True, 'Mongolia', 'Mongolia'),
(145, '498', 'MD', 'MDA', 'Moldavsko', 'Moldavská republika', True, 'Republic of Moldova', 'Republic of Moldova'),
(146, '499', 'ME', 'MNE', 'Čierna Hora', 'Čierna Hora', True, 'Montenegro', 'Montenegro'),
(147, '500', 'MS', 'MSR', 'Montserrat', 'Montserrat', True, 'Montserrat', 'Montserrat'),
(148, '504', 'MA', 'MAR', 'Maroko', 'Marocké kráľovstvo', True, 'Kingdom of Morocco', 'Morocco'),
(149, '508', 'MZ', 'MOZ', 'Mozambik', 'Mozambická republika', True, 'Republic of Mozambique', 'Mozambique'),
(150, '512', 'OM', 'OMN', 'Omán', 'Ománsky sultanát', True, 'Sultanate of Oman', 'Oman'),
(151, '516', 'NA', 'NAM', 'Namíbia', 'Namíbijská republika', True, 'Republic of Namibia', 'Namibia'),
(152, '520', 'NR', 'NRU', 'Nauru', 'Nauruská republika', True, 'Republic of Nauru', 'Nauru'),
(153, '524', 'NP', 'NPL', 'Nepál', 'Nepálská federatívna demokratická republika', True, 'Federal Democratic Republic of Nepal', 'Nepal'),
(154, '528', 'NL', 'NLD', 'Holandsko', 'Holandské kráľovstvo', True, 'Kingdom of the Netherlands', 'Netherlands'),
(155, '530', 'AN', 'ANT', 'Holandské Antily', 'Holandské Antily', False, 'Netherlands Antilles', 'Netherlands Antilles'),
(156, '531', 'CW', 'CUW', 'Curaçao', 'Curaçao', True, 'Curaçao', 'Curaçao'),
(157, '532', 'AN', 'N/A', 'Holandské Antily', 'Holandské Antily', False, 'Netherlands Antilles', 'Netherlands Antilles'),
(158, '533', 'AW', 'ABW', 'Aruba', 'Aruba', True, 'Aruba', 'Aruba'),
(159, '534', 'SX', 'SXM', 'Svätý Martin (holand.č.)', 'Svätý Martin (holandská časť)', True, 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch p.)'),
(160, '535', 'BQ', 'BES', 'Bonaire,Sv.Eustach,Saba', 'Bonaire, Svätý Eustach a Saba', True, 'Bonaire, Sint Eustatius and Saba', 'Bonaire,S.Eustatius,Saba'),
(161, '536', 'NT', 'N/A', 'Neutrálne územia', 'Neutrálne územia Ruchajmija, Váfra, Andza', False, 'Neutral Zone', 'Neutral Zone'),
(162, '540', 'NC', 'NCL', 'Nová Kaledónia', 'Nová Kaledónia', True, 'New Caledonia', 'New Caledonia'),
(163, '548', 'VU', 'VUT', 'Vanuatu', 'Vanuatská republika', True, 'Republic of Vanuatu', 'Vanuatu'),
(164, '554', 'NZ', 'NZL', 'Nový Zéland', 'Nový Zéland', True, 'New Zealand', 'New Zealand'),
(165, '558', 'NI', 'NIC', 'Nikaragua', 'Nikaragujská republika', True, 'Republic of Nicaragua', 'Nicaragua'),
(166, '562', 'NE', 'NER', 'Niger', 'Nigerská republika', True, 'Republic of the Niger', 'Niger'),
(167, '566', 'NG', 'NGA', 'Nigéria', 'Nigérijská federatívna republika', True, 'Federal Republic of Nigeria', 'Nigeria'),
(168, '570', 'NU', 'NIU', 'Niue', 'Niue', True, 'Niue', 'Niue'),
(169, '574', 'NF', 'NFK', 'Norfolk', 'Teritórium ostrova Norfolk', True, 'Territory of Norfolk Island', 'Norfolk Island'),
(170, '578', 'NO', 'NOR', 'Nórsko', 'Nórske kráľovstvo', True, 'Kingdom of Norway', 'Norway'),
(171, '580', 'MP', 'MNP', 'Severné Mariány', 'Spoločenstvo ostrovov Severné Mariány', True, 'Commonwealth of the Northern Mariana Islands', 'Northern Mariana Islands'),
(172, '581', 'UM', 'UMI', 'Menšie odľahlé ostr.USA', 'Menšie odľahlé ostrovy Spojených štátov', True, 'United States Minor Outlying Islands', 'US Minor Outlying Isl.'),
(173, '583', 'FM', 'FSM', 'Mikronézia', 'Mikronézske federatívne štáty', True, 'Federated States of Micronesia', 'Micronesia (Fed.St. of)'),
(174, '584', 'MH', 'MHL', 'Marshallove ostrovy', 'Republika Marshallových ostrovov', True, 'Republic of the Marshall Islands', 'Marshall Islands'),
(175, '585', 'PW', 'PLW', 'Palau', 'Palauská republika', True, 'Republic of Palau', 'Palau'),
(176, '586', 'PK', 'PAK', 'Pakistan', 'Pakistanská islamská republika', True, 'Islamic Republic of Pakistan', 'Pakistan'),
(177, '590', 'PA', 'N/A', 'Panama', 'Panamská republika', False, 'Republic of Panama', 'Panama'),
(178, '591', 'PA', 'PAN', 'Panama', 'Panamská republika', True, 'Republic of Panama', 'Panama'),
(179, '598', 'PG', 'PNG', 'Papua-Nová Guinea', 'Nezávislý štát Papua-Nová Guinea', True, 'Independent State of Papua New Guinea', 'Papua New Guinea'),
(180, '600', 'PY', 'PRY', 'Paraguaj', 'Paraguajská republika', True, 'Republic of Paraguay', 'Paraguay'),
(181, '604', 'PE', 'PER', 'Peru', 'Peruánska republika', True, 'Republic of Peru', 'Peru'),
(182, '608', 'PH', 'PHL', 'Filipíny', 'Filipínska republika', True, 'Republic of the Philippines', 'Philippines'),
(183, '612', 'PN', 'PCN', 'Pitcairnove ostrovy', 'Pitcairnove ostrovy', True, 'Pitcairn Islands', 'Pitcairn'),
(184, '616', 'PL', 'POL', 'Poľsko', 'Poľská republika', True, 'Republic of Poland', 'Poland'),
(185, '620', 'PT', 'PRT', 'Portugalsko', 'Portugalská republika', True, 'Portuguese Republic', 'Portugal'),
(186, '624', 'GW', 'GNB', 'Guinea-Bissau', 'Guinejsko-bissauská republika', True, 'Republic of Guinea-Bissau', 'Guinea-Bissau'),
(187, '626', 'TL', 'TLS', 'Východný Timor', 'Východotimorská demokratická republika', True, 'Democratic Republic of Timor-Leste', 'Timor-Leste'),
(188, '630', 'PR', 'PRI', 'Portoriko', 'Portorické spoločenstvo', True, 'Puerto Rico', 'Puerto Rico'),
(189, '634', 'QA', 'QAT', 'Katar', 'Katarský štát', True, 'State of Qatar', 'Qatar'),
(190, '638', 'RE', 'REU', 'Réunion', 'Réunion', True, 'Réunion', 'Réunion'),
(191, '642', 'RO', 'ROU', 'Rumunsko', 'Rumunsko', True, 'Romania', 'Romania'),
(192, '643', 'RU', 'RUS', 'Rusko', 'Ruská federácia', True, 'Russian Federation', 'Russian Federation'),
(193, '646', 'RW', 'RWA', 'Rwanda', 'Rwandská republika', True, 'Republic of Rwanda', 'Rwanda'),
(194, '652', 'BL', 'BLM', 'Svätý Bartolomej', 'Svätý Bartolomej', True, 'Saint Barthélemy', 'Saint Barthélemy'),
(195, '654', 'SH', 'SHN', 'Sv.Helena,Asc,Trist.daC.', 'Svätá Helena, Ascension a Tristan da Cunha', True, 'Saint Helena, Ascension and Tristan da Cunha', 'St.Helena,Asc,Trist.daC.'),
(196, '659', 'KN', 'KNA', 'Svätý Krištof a Nevis', 'Federácia Svätého Krištofa a Nevisu', True, 'Saint Kitts and Nevis', 'Saint Kitts and Nevis'),
(197, '660', 'AI', 'AIA', 'Anguilla', 'Anguilla', True, 'Anguilla', 'Anguilla'),
(198, '662', 'LC', 'LCA', 'Svätá Lucia', 'Svätá Lucia', True, 'Saint Lucia', 'Saint Lucia'),
(199, '663', 'MF', 'MAF', 'Svätý Martin (franc.č.)', 'Svätý Martin', True, 'Saint Martin', 'Saint Martin (French p.)'),
(200, '666', 'PM', 'SPM', 'Saint Pierre a Miquelon', 'Saint Pierre a Miquelon', True, 'Saint Pierre and Miquelon', 'St. Pierre and Miquelon'),
(201, '670', 'VC', 'VCT', 'Sv. Vincent a Grenadíny', 'Svätý Vincent a Grenadíny', True, 'Saint Vincent and the Grenadines', 'St.Vincent,the Grenadin.'),
(202, '674', 'SM', 'SMR', 'San Maríno', 'Sanmarínska republika', True, 'Republic of San Marino', 'San Marino'),
(203, '678', 'ST', 'STP', 'Sv. Tomáš a Princov ost.', 'Demokratická republika Svätého Tomáša a Princovho ostrova', True, 'Democratic Republic of Sao Tome and Principe', 'Sao Tome and Principe'),
(204, '682', 'SA', 'SAU', 'Saudská Arábia', 'Saudskoarabské kráľovstvo', True, 'Kingdom of Saudi Arabia', 'Saudi Arabia'),
(205, '686', 'SN', 'SEN', 'Senegal', 'Senegalská republika', True, 'Republic of Senegal', 'Senegal'),
(206, '688', 'RS', 'SRB', 'Srbsko', 'Srbská republika', True, 'Republic of Serbia', 'Serbia'),
(207, '690', 'SC', 'SYC', 'Seychely', 'Seychelská republika', True, 'Republic of Seychelles', 'Seychelles'),
(208, '694', 'SL', 'SLE', 'Sierra Leone', 'Sierraleonská republika', True, 'Republic of Sierra Leone', 'Sierra Leone'),
(209, '702', 'SG', 'SGP', 'Singapur', 'Singapurská republika', True, 'Republic of Singapore', 'Singapore'),
(210, '703', 'SK', 'SVK', 'Slovensko', 'Slovenská republika', True, 'Slovak Republic', 'Slovakia'),
(211, '704', 'VN', 'VNM', 'Vietnam', 'Vietnamská socialistická republika', True, 'Socialist Republic of Viet Nam', 'Viet Nam'),
(212, '705', 'SI', 'SVN', 'Slovinsko', 'Slovinská republika', True, 'Republic of Slovenia', 'Slovenia'),
(213, '706', 'SO', 'SOM', 'Somálsko', 'Somálska federatívna republika', True, 'Federal Republic of Somalia', 'Somalia'),
(214, '710', 'ZA', 'ZAF', 'Južná Afrika', 'Juhoafrická republika', True, 'Republic of South Africa', 'South Africa'),
(215, '716', 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwianska republika', True, 'Republic of Zimbabwe', 'Zimbabwe'),
(216, '724', 'ES', 'ESP', 'Španielsko', 'Španielske kráľovstvo', True, 'Kingdom of Spain', 'Spain'),
(217, '728', 'SS', 'SSD', 'Južný Sudán', 'Juhosudánska republika', True, 'Republic of South Sudan', 'South Sudan'),
(218, '729', 'SD', 'SDN', 'Sudán', 'Sudánska republika', True, 'Republic of the Sudan', 'Sudan'),
(219, '732', 'EH', 'ESH', 'Západná Sahara', 'Západná Sahara', True, 'Western Sahara', 'Western Sahara'),
(220, '736', 'SD', 'SDN', 'Sudán', 'Sudánska republika', False, 'Republic of the Sudan', 'Sudan'),
(221, '740', 'SR', 'SUR', 'Surinam', 'Surinamská republika', True, 'Republic of Suriname', 'Suriname'),
(222, '744', 'SJ', 'SJM', 'Svalbard a Jan Mayen', 'Svalbard a Jan Mayen', True, 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'),
(223, '748', 'SZ', 'SWZ', 'Svazijsko', 'Svazijské kráľovstvo', True, 'Kingdom of Swaziland', 'Swaziland'),
(224, '752', 'SE', 'SWE', 'Švédsko', 'Švédske kráľovstvo', True, 'Kingdom of Sweden', 'Sweden'),
(225, '756', 'CH', 'CHE', 'Švajčiarsko', 'Švajčiarska konfederácia', True, 'Swiss Confederation', 'Switzerland'),
(226, '760', 'SY', 'SYR', 'Sýria', 'Sýrska arabská republika', True, 'Syrian Arab Republic', 'Syrian Arab Republic'),
(227, '762', 'TJ', 'TJK', 'Tadžikistan', 'Tadžická republika', True, 'Republic of Tajikistan', 'Tajikistan'),
(228, '764', 'TH', 'THA', 'Thajsko', 'Thajské kráľovstvo', True, 'Kingdom of Thailand', 'Thailand'),
(229, '768', 'TG', 'TGO', 'Togo', 'Togská republika', True, 'Togolese Republic', 'Togo'),
(230, '772', 'TK', 'TKL', 'Tokelau', 'Tokelauské ostrovy', True, 'Tokelau Islands', 'Tokelau'),
(231, '776', 'TO', 'TON', 'Tonga', 'Tongské kráľovstvo', True, 'Kingdom of Tonga', 'Tonga'),
(232, '780', 'TT', 'TTO', 'Trinidad a Tobago', 'Republika Trinidadu a Tobaga', True, 'Republic of Trinidad and Tobago', 'Trinidad and Tobago'),
(233, '784', 'AE', 'ARE', 'Spojené arabské emiráty', 'Spojené arabské emiráty', True, 'United Arab Emirates', 'United Arab Emirates'),
(234, '788', 'TN', 'TUN', 'Tunisko', 'Tuniská republika', True, 'Republic of Tunisia', 'Tunisia'),
(235, '792', 'TR', 'TUR', 'Turecko', 'Turecká republika', True, 'Republic of Turkey', 'Turkey'),
(236, '795', 'TM', 'TKM', 'Turkménsko', 'Turkménsko', True, 'Turkmenistan', 'Turkmenistan'),
(237, '796', 'TC', 'TCA', 'Turks a Caicos', 'Ostrovy Turks a Caicos', True, 'Turks and Caicos Islands', 'Turks and Caicos Islands'),
(238, '798', 'TV', 'TUV', 'Tuvalu', 'Tuvalu', True, 'Tuvalu', 'Tuvalu'),
(239, '800', 'UG', 'UGA', 'Uganda', 'Ugandská republika', True, 'Republic of Uganda', 'Uganda'),
(240, '804', 'UA', 'UKR', 'Ukrajina', 'Ukrajina', True, 'Ukraine', 'Ukraine'),
(241, '807', 'MK', 'MKD', 'Macedónsko', 'Macedónska republika', True, 'The Former Yugoslav Republic of Macedonia', 'Form.Yug.R.of Macedonia'),
(242, '810', 'SU', 'N/A', 'Spol.nezávislých štátov', 'Spoločenstvo nezávislých štátov', False, 'Commonwealth of Independent States', 'CIS'),
(243, '818', 'EG', 'EGY', 'Egypt', 'Egyptská arabská republika', True, 'Arab Republic of Egypt', 'Egypt'),
(244, '826', 'GB', 'GBR', 'Spojené kráľovstvo', 'Spojené kráľovstvo Veľkej Británie a Severného Írska', True, 'United Kingdom of Great Britain and Northern Ireland', 'United Kingd.of GB a.NI.'),
(245, '831', 'GG', 'GGY', 'Guernsey', 'Guernsey', True, 'Guernsey', 'Guernsey'),
(246, '832', 'JE', 'JEY', 'Jersey', 'Jersey', True, 'Jersey', 'Jersey'),
(247, '833', 'IM', 'IMN', 'Man', 'Ostrov Man', True, 'Isle of Man, Dependency of the Crown', 'Isle of Man'),
(248, '834', 'TZ', 'TZA', 'Tanzánia', 'Tanzánijská zjednotená republika', True, 'United Republic of Tanzania', 'United Rep.of Tanzania'),
(249, '840', 'US', 'USA', 'Spojené štáty, USA', 'Spojené štáty americké', True, 'United States of America', 'United States of America'),
(250, '850', 'VI', 'VIR', 'Americké Panenské ostr.', 'Panenské ostrovy Spojených štátov', True, 'Virgin Islands of the United States', 'Virgin Islands of the US'),
(251, '854', 'BF', 'BFA', 'Burkina', 'Burkina Faso', True, 'Burkina Faso', 'Burkina Faso'),
(252, '858', 'UY', 'URY', 'Uruguaj', 'Uruguajská východná republika', True, 'Eastern Republic of Uruguay', 'Uruguay'),
(253, '860', 'UZ', 'UZB', 'Uzbekistan', 'Uzbecká republika', True, 'Republic of Uzbekistan', 'Uzbekistan'),
(254, '862', 'VE', 'VEN', 'Venezuela', 'Venezuelská bolívarovská republika', True, 'Bolivarian Republic of Venezuela', 'Venezuela (Bol.Rep.of)'),
(255, '876', 'WF', 'WLF', 'Wallis a Futuna', 'Wallis a Futuna', True, 'Wallis and Futuna', 'Wallis and Futuna'),
(256, '882', 'WS', 'WSM', 'Samoa', 'Samojský nezávislý štát', True, 'Independent State of Samoa', 'Samoa'),
(257, '887', 'YE', 'YEM', 'Jemen', 'Jemenská republika', True, 'Republic of Yemen', 'Yemen'),
(258, '891', 'CS', 'SCG', 'Srbsko a Čierna Hora', 'Srbsko a Čierna Hora', False, 'Serbia and Montenegro', 'Serbia and Montenegro'),
(259, '894', 'ZM', 'ZMB', 'Zambia', 'Zambijská republika', True, 'Republic of Zambia', 'Zambia'),
(260, '896', 'N/', 'N/A', 'Oblasti inde nešpecifik.', 'Oblasti inde nešpecifikované', True, 'Areas not elsewhere specified', 'Areas not specified'),
(261, '898', 'N/', 'N/A', 'Nešpecifikované', 'Nešpecifikované', True, 'Not specified', 'Not specified'),
(262, '973', 'XC', 'N/A', 'Macedónsko', 'Macedónska republika', False, 'Republic of Macedonia', 'Macedonia');