/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 15-feb-2022 20:57:13 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS sub.address_idaddress_seq
;

DROP SEQUENCE IF EXISTS aud.error_iderror_seq
;

DROP SEQUENCE IF EXISTS sub.subject_idsubject_seq
;

DROP SEQUENCE IF EXISTS aud.trace_idtrace_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS sub."Address" CASCADE
;

DROP TABLE IF EXISTS sub."AddressType" CASCADE
;

DROP TABLE IF EXISTS sub."Attachment" CASCADE
;

DROP TABLE IF EXISTS sub."Country" CASCADE
;

DROP TABLE IF EXISTS aud."Error" CASCADE
;

DROP TABLE IF EXISTS aud."LogLevel" CASCADE
;

DROP TABLE IF EXISTS sub."Subject" CASCADE
;

DROP TABLE IF EXISTS aud."Trace" CASCADE
;

/* Create Tables */

CREATE TABLE sub."Address"
(
	"IdAddress" integer NOT NULL   DEFAULT NEXTVAL(('sub."address_idaddress_seq"'::text)::regclass),
	"CityName" varchar(127) NULL,
	"Zip" varchar(15) NULL,
	"IdCountry" integer NULL,
	"StreetName" varchar(127) NULL,
	"StreetNumber" varchar(31) NULL,
	"ValidTo" timestamp without time zone NULL,
	"IdSubject" integer NULL,
	"IdAddressType" integer NULL
)
;

CREATE TABLE sub."AddressType"
(
	"IdAddressType" integer NOT NULL,
	"Value" varchar(63) NOT NULL,
	"Description" varchar(50) NULL,
	"ValitdTo" timestamp without time zone NULL
)
;

CREATE TABLE sub."Attachment"
(
	"IdAttachment" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"Extension" varchar(7) NOT NULL,
	"Size" numeric NOT NULL,
	"RelativePath" varchar(127) NOT NULL,
	"ContentType" varchar(127) NOT NULL,
	"IdSubject" integer NULL,
	"DeletedAt" timestamp without time zone NULL
)
;

CREATE TABLE sub."Country"
(
	"IdCountry" integer NOT NULL,
	"Code" varchar(7) NOT NULL,
	"Acronym2" varchar(3) NOT NULL,
	"Acronym3" varchar(3) NOT NULL,
	"NameSKShort" varchar(127) NOT NULL,
	"NameSK" varchar(127) NOT NULL,
	"NameEN" varchar(127) NOT NULL,
	"NameENShort" varchar(127) NOT NULL,
	"IsValid" boolean NOT NULL   DEFAULT TRUE
)
;

CREATE TABLE aud."Error"
(
	"IdError" bigint NOT NULL   DEFAULT NEXTVAL(('aud."error_iderror_seq"'::text)::regclass),
	"Created" timestamp without time zone NOT NULL,
	"IdLogLevel" integer NULL,
	"Level" varchar(63) NULL,
	"CallerMethodFullName" varchar(127) NULL,
	"Message" text NULL,
	"Exception" text NULL,
	"Detail" text NULL,
	"SqlStatement" jsonb NULL,
	"IdUser" integer NULL,
	"ClientIp" varchar(63) NULL,
	"Environment" varchar(127) NULL,
	"ClientAgent" varchar(255) NULL,
	"ExceptionMessage" text NULL,
	"RequestPath" varchar(255) NULL,
	"RequestId" varchar(63) NULL,
	"RequestMethod" varchar(31) NULL,
	"MachineName" varchar(127) NULL,
	"ProcesId" varchar(63) NULL,
	"ThreadId" varchar(63) NULL
)
;

CREATE TABLE aud."LogLevel"
(
	"IdLogLevel" integer NOT NULL,
	"LogLevel" varchar(63) NULL,
	"ValidTo" timestamp without time zone NULL
)
;

CREATE TABLE sub."Subject"
(
	"IdSubject" integer NOT NULL   DEFAULT NEXTVAL(('sub."subject_idsubject_seq"'::text)::regclass),
	"FirstName" varchar(63) NULL,
	"LastName" varchar(63) NULL,
	"Email" varchar(127) NULL,
	"TelNumber" varchar(63) NULL,
	"PersonalIdentificationNumber" varchar(31) NULL,
	"BusinessIdentificationNumber" varchar(31) NULL,
	"BirthDate" timestamp without time zone NULL,
	"ResidenceCardValidTo" timestamp without time zone NULL,
	"Note" text NULL,
	"ValidTo" timestamp without time zone NULL
)
;

CREATE TABLE aud."Trace"
(
	"IdTrace" bigint NOT NULL   DEFAULT NEXTVAL(('aud."trace_idtrace_seq"'::text)::regclass),
	"Created" timestamp without time zone NOT NULL,
	"IdLogLevel" integer NULL,
	"Level" varchar(63) NULL,
	"CallerMethodFullName" varchar(127) NULL,
	"Message" text NULL,
	"IdUser" integer NULL,
	"ClientIp" varchar(63) NULL,
	"ClientAgent" varchar(255) NULL,
	"RequestPath" varchar(255) NULL,
	"RequestId" varchar(63) NULL,
	"RequestMethod" varchar(31) NULL,
	"MachineName" varchar(127) NULL,
	"ProcesId" varchar(63) NULL,
	"ThreadId" varchar(63) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE sub."Address" ADD CONSTRAINT "PK_Address"
	PRIMARY KEY ("IdAddress")
;

CREATE INDEX "IXFK_Address_AddressType" ON sub."Address" ("IdAddressType" ASC)
;

CREATE INDEX "IXFK_Address_Country" ON sub."Address" ("IdCountry" ASC)
;

CREATE INDEX "IXFK_Address_Subject" ON sub."Address" ("IdSubject" ASC)
;

ALTER TABLE sub."AddressType" ADD CONSTRAINT "PK_AddressType"
	PRIMARY KEY ("IdAddressType")
;

ALTER TABLE sub."Attachment" ADD CONSTRAINT "PK_Attachment"
	PRIMARY KEY ("IdAttachment")
;

CREATE INDEX "IXFK_Attachment_Subject" ON sub."Attachment" ("IdSubject" ASC)
;

ALTER TABLE sub."Country" ADD CONSTRAINT "PK_Country"
	PRIMARY KEY ("IdCountry")
;

ALTER TABLE aud."Error" ADD CONSTRAINT "PK_Error"
	PRIMARY KEY ("IdError")
;

CREATE INDEX "IXFK_Error_LogLevel" ON aud."Error" ("IdLogLevel" ASC)
;

ALTER TABLE aud."LogLevel" ADD CONSTRAINT "PK_LogLevel"
	PRIMARY KEY ("IdLogLevel")
;

ALTER TABLE sub."Subject" ADD CONSTRAINT "PK_Subject"
	PRIMARY KEY ("IdSubject")
;

ALTER TABLE aud."Trace" ADD CONSTRAINT "PK_Trace"
	PRIMARY KEY ("IdTrace")
;

CREATE INDEX "IXFK_Trace_LogLevel" ON aud."Trace" ("IdLogLevel" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE sub."Address" ADD CONSTRAINT "FK_Address_AddressType"
	FOREIGN KEY ("IdAddressType") REFERENCES sub."AddressType" ("IdAddressType") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sub."Address" ADD CONSTRAINT "FK_Address_Country"
	FOREIGN KEY ("IdCountry") REFERENCES sub."Country" ("IdCountry") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sub."Address" ADD CONSTRAINT "FK_Address_Subject"
	FOREIGN KEY ("IdSubject") REFERENCES sub."Subject" ("IdSubject") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sub."Attachment" ADD CONSTRAINT "FK_Attachment_Subject"
	FOREIGN KEY ("IdSubject") REFERENCES sub."Subject" ("IdSubject") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE aud."Error" ADD CONSTRAINT "FK_Error_LogLevel"
	FOREIGN KEY ("IdLogLevel") REFERENCES aud."LogLevel" ("IdLogLevel") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE aud."Trace" ADD CONSTRAINT "FK_Trace_LogLevel"
	FOREIGN KEY ("IdLogLevel") REFERENCES aud."LogLevel" ("IdLogLevel") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE sub.address_idaddress_seq INCREMENT 1 START 1
;

CREATE SEQUENCE aud.error_iderror_seq INCREMENT 1 START 1
;

CREATE SEQUENCE sub.subject_idsubject_seq INCREMENT 1 START 1
;

CREATE SEQUENCE aud.trace_idtrace_seq INCREMENT 1 START 1
;
