/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 01-feb-2022 15:27:52 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS sub."Addresses" CASCADE
;

DROP VIEW IF EXISTS sub."Attachments" CASCADE
;

DROP VIEW IF EXISTS sub."Subjects" CASCADE
;

DROP VIEW IF EXISTS evn."UserEvents" CASCADE
;

/* Create Views */

CREATE VIEW sub."Addresses" AS 
SELECT 
	a."IdAddress", 
	a."CityName", 
	a."Zip", 
	a."IdCountry", 
	a."StreetName", 
	a."StreetNumber", 
	a."ValidTo", 
	a."IdSubject", 
	a."IdAddressType",
	at2."Value" as "AddressTypeDescription",
	c."Acronym2" as "CountryAkronym2",
	c."Acronym3" as "CountryAkronym3",
	c."NameEN" as "CountryNameEN",
	c."NameENShort" as "CountryNameENShort",
	c."NameSK" as "CountryNameSK",
	c."NameSKShort"  as "CountryNameSKShort" 
FROM 
	sub."Address" a
join 
	sub."AddressType" at2 on a."IdAddressType" = at2."IdAddressType" 
join 
	sub."Country" c on c."IdCountry" = a."IdCountry"
;

CREATE VIEW sub."Attachments" AS 
SELECT 
	"IdAttachment", 
	"Name", 
	"Extension", 
	"Size", 
	"RelativePath", 
	"ContentType", 
	"IdSubject", 
	"DeletedAt"
FROM 
	sub."Attachment";
;

CREATE VIEW sub."Countries" AS 
SELECT 
	"IdCountry", 
	"Code", 
	"Acronym2", 
	"Acronym3", 
	"NameSKShort", 
	"NameSK", 
	"NameEN", 
	"NameENShort", 
	"IsValid"
FROM 
	sub."Country"
;

CREATE VIEW sub."Subjects" AS 
SELECT 
	s."IdSubject",
    s."FirstName",
    s."LastName",
    s."Email",
    s."TelNumber",
    s."PersonalIdentificationNumber",
    s."BusinessIdentificationNumber",
    s."BirthDate",
    s."ResidenceCardValidTo",
    s."Note",
    s."ValidTo",
    string_agg(concat(a."StreetName", ' ', a."StreetNumber", ', ', a."Zip", ' ',a."CityName", ', ', c."NameSK"), '; ') as "FullAddress"
FROM 
	sub."Subject" s
left join 
	sub."Address" a on a."IdSubject" = s."IdSubject"
left join 
	sub."Country" c on c."IdCountry" = a."IdCountry"
where a."IdAddressType" = 1
group by s."IdSubject"
;

CREATE VIEW evn."UserEvents" AS 
SELECT 
	ue."IdUserEvent", 
	ue."Name", 
	ue."Decsription", 
	ue."DueDate", 
	ue."NotificationDate", 
	ue."TerminationDate", 
	ue."DeletedDate", 
	ue."IdSubject",
	s."LastName",
	s."FirstName",
	s."ValidTo",
	s."Email",
	s."TelNumber",
	s."PersonalIdentificationNumber",
	s."BusinessIdentificationNumber",
	s."BirthDate",
	s."ResidenceCardValidTo",
	concat(s."LastName", ' ', s."FirstName") as "Subject_FullName"
FROM 
	evn."UserEvent" ue
left join
	sub."Subject" s on s."IdSubject" = ue."IdSubject" 
;