/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 01-feb-2022 15:27:52 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS sub."Subjects" CASCADE
;

DROP VIEW IF EXISTS sub."Attachments" CASCADE
;

/* Create Views */

CREATE VIEW sub."Subjects" AS 
SELECT 
	"IdSubject", 
	"FirstName", 
	"LastName", 
	"Email", 
	"TelNumber", 
	"PersonalIdentificationNumber", 
	"BusinessIdentificationNumber", 
	"BirthDate", 
	"ResidenceCardValidTo", 
	"Note",
	"ValidTo"
FROM 
	sub."Subject"
;

CREATE VIEW sub."Addresses" AS 
SELECT 
	a."IdAddress", 
	a."CityName", 
	a."Zip", 
	a."IdCountry", 
	a."StreetName", 
	a."StreetNumber", 
	a."ValidTo", 
	a."IdSubject", 
	a."IdAddressType",
	at2."Value" as "AddressTypeDescription",
	c."Acronym2" as "CountryAkronym2",
	c."Acronym3" as "CountryAkronym3",
	c."NameEN" as "CountryNameEN",
	c."NameENShort" as "CountryNameENShort",
	c."NameSK" as "CountryNameSK",
	c."NameSKShort"  as "CountryNameSKShort" 
FROM 
	sub."Address" a
join 
	sub."AddressType" at2 on a."IdAddressType" = at2."IdAddressType" 
join 
	sub."Country" c on c."IdCountry" = a."IdCountry"
;

CREATE VIEW sub."Countries" AS 
SELECT 
	"IdCountry", 
	"Code", 
	"Acronym2", 
	"Acronym3", 
	"NameSKShort", 
	"NameSK", 
	"NameEN", 
	"NameENShort", 
	"IsValid"
FROM 
	sub."Country"
;

CREATE VIEW sub."Attachments" AS 
SELECT 
	"IdAttachment", 
	"Name", 
	"Extension", 
	"Size", 
	"RelativePath", 
	"ContentType", 
	"IdSubject", 
	"DeletedAt"
FROM 
	sub."Attachment";
;